apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ds7c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-ds7c
    app.kubernetes.io/part-of: test-rhtap-40-app
  name: devfile-sample-code-with-quarkus-ds7c
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ds7c
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ds7c
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-40-tenant/test-rhtap-40-app/devfile-sample-code-with-quarkus-ds7c@sha256:6f5ec6c337afff3c8dcd48a46c980655e518302bc7641e8ba9ec033c366ae3ac
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
