apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-ds7c
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-40-tenant/test-rhtap-40-app/devfile-sample-code-with-quarkus-ds7c@sha256:6f5ec6c337afff3c8dcd48a46c980655e518302bc7641e8ba9ec033c366ae3ac
        name: my-java-quarkus
        resources: {}
status: {}
